### ISSUE TITLE
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (uri:"", local:"rucComprobante"). Expected elements are <{}statusCdr> 

### ISSUE THREAD

**Issue by geraldvaras** [project-openubl/xsender#15]
Estoy intentando ejecutar el metodo **getStatusCDR** de la clase **BillConsultServiceManager** pero obtengo una excepcion **SOAPFaultException**

El metodo que estoy empleando para ejecutarlo es el siguiente:
`    public void assertConsultToSunat(String ruc, String documentType , String serie, Integer numero, BillServiceModel.Status estado) throws Exception{
        ServiceConfig serviceConfig = new ServiceConfig.Builder()
                .url(WEBSERVICE_URL)
                .username(WEBSERVICE_USERNAME)
                .password(WEBSERVICE_PASSWORD)
                .build();
        BillConsultModel consulta = new BillConsultModel.Builder()
                .ruc(ruc)
                .serie(serie)
                .numero(numero)
                .tipo(documentType)
                .build();
        StatusResponse statusResponse = BillConsultServiceManager.getStatusCdr(consulta, serviceConfig);
        assertEquals(statusResponse.getStatusCode(),estado);
    }`

Lo cual me deberia devolver una instancia de la clase StatusResponse
sin embargo obtengo el error:
`
javax.xml.ws.soap.SOAPFaultException: Unmarshalling Error: unexpected element (uri:"", local:"rucComprobante"). Expected elements are <{}statusCdr> 

	at org.apache.cxf.jaxws.JaxWsClientProxy.mapException(JaxWsClientProxy.java:195)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:145)
	at com.sun.proxy.$Proxy193.getStatusCdr(Unknown Source)
	at io.github.project.openubl.xmlsenderws.webservices.wrappers.BillConsultServiceWrapper.getStatusCdr(BillConsultServiceWrapper.java:44)
	at io.github.project.openubl.xmlsenderws.webservices.managers.BillConsultServiceManager.getStatusCdr(BillConsultServiceManager.java:34)
Caused by: org.apache.cxf.binding.soap.SoapFault: Unmarshalling Error: unexpected element (uri:"", local:"rucComprobante"). Expected elements are <{}statusCdr> `

Adjunto el soap response del servidor
`
ID: 1
Response-Code: 500
Encoding: UTF-8
Content-Type: text/xml;charset=UTF-8
Headers: {Content-Length=[308], content-type=[text/xml;charset=UTF-8], Date=[Mon, 21 Sep 2020 20:51:39 GMT], Server=[JBoss-EAP/7], X-Powered-By=[Undertow/1]}
Payload: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Client</faultcode><faultstring>Unmarshalling Error: unexpected element (uri:"", local:"rucComprobante"). Expected elements are &lt;{}statusCdr> </faultstring></soap:Fault></soap:Body></soap:Envelope>`

**Comment by carlosthe19916** [comment]
@geraldvaras No veo ningun problema en el método que adjuntaste, excepto la linea `assertEquals(statusResponse.getStatusCode(), estado);` ya que estas comparando dos tipos de datos distintos. Acá adjunto tu código con algunas modificaciones para hacer que funcione correctamente:

```
@Test
public void testConsultToSunat () throws IOException {
    assertConsultToSunat("myRUC", Catalogo1.FACTURA.getCode(), "F001", 20);
}

public void assertConsultToSunat(String ruc, String documentType, String serie, Integer numero) throws IOException {
    ServiceConfig serviceConfig = new ServiceConfig.Builder()
            .url("https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService")
            .username(WEBSERVICE_USERNAME)
            .password(WEBSERVICE_PASSWORD)
            .build();

    BillConsultModel consulta = new BillConsultModel.Builder()
            .ruc(ruc)
            .serie(serie)
            .numero(numero)
            .tipo(documentType)
            .build();

    // Fetch data from SUNAT
    service.sunat.gob.pe.billconsultservice.StatusResponse statusResponse = BillConsultServiceManager.getStatusCdr(consulta, serviceConfig);

    // Verify data Invoice exists in SUNAT
    assertEquals(statusResponse.getStatusCode(), "0004");
    assertEquals(statusResponse.getStatusMessage(), "La constancia existe");
    assertNotNull(statusResponse.getContent());

    // Write the CRD to your filesystem
    Path path = Paths.get("/home/guest/myCrd.zip");
    Files.write(path, statusResponse.getContent());
}
```

Los puntos en los que debes de tener cuidado:
- Tu recibes un parámetro `String documentType` verifica que su valor es el correcto. Los posibles valores se encuentran en el Catalogo1. Te recomiendo usar el ENUM disponible en la libreria, tal y como se muestra en el ejemplo.
- **WEBSERVICE_URL** te recomiendo usar https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService . Si usas una OSE consulta con tu OSE y verifica que exponen los servicios de consulta para CDR, en caso contrario usa la URL del ejemplo.
- **statusResponse.getStatusCode()** Devuelve un código en forma de "String"
- **statusResponse.getContent()** Devuelve el CRD del comprobante en forma de ZIP.
- **BillConsultServiceManager.getStatusCRD** solo funciona en producción ya que la SUNAT no tiene una URL beta para consultas.
- Verifica que tu usuario tenga el perfil adecuado para hacer consultas y recuperar CRDs

Como extra, acá tienes el código de ejemplo funcionando al 100% sin ninguna clase de error. Solo copia y pega el ejemplo que te compartí. Me comestas si solucionaste tu problema.

![Screenshot from 2020-09-22 08-45-12_11](https://user-images.githubusercontent.com/2582866/93852436-4f1e8580-fcb2-11ea-8239-724f130a4cce.png)

> Recuerda que este es un proyecto Open Source y puedes colaborar dándole una estrella al proyecto, sugiriendo mejoras, reportando errores, etc.

**Comment by geraldvaras** [comment]
@carlosthe19916 Gracias por la pronta respuesta.
Te comento hice las modificaciones que me indicaste en el método, sin embargo sigo obteniendo el mismo error. (Adjunto screen)
![imagen](https://user-images.githubusercontent.com/882405/93893108-e2f05180-fcb2-11ea-8d11-7bcaae29dad1.png)
Me puse a depurar el soap request con SoapUI y me acabo de percatar que necesita incluir los parámetros con la etiqueta `<statusCdr>` para que la llamada pueda funcionar, adicional a esto el parámetro de numero de comprobante lo he tenido que completar con 0s para que me devuelva el cdr caso contrario me indica que el ticket no existe.
![imagen](https://user-images.githubusercontent.com/882405/93905264-619fbb80-fcc0-11ea-87f0-46bcb9232c2e.png)
![imagen](https://user-images.githubusercontent.com/882405/93905097-31f0b380-fcc0-11ea-9c26-112feeb270f1.png)
![imagen](https://user-images.githubusercontent.com/882405/93905126-3a48ee80-fcc0-11ea-9014-eab42d1b5eff.png)

De antemano te agradezco la respuesta y por tu valioso tiempo.

**Comment by carlosthe19916** [comment]
@geraldvaras el ejemplo que adjuntas me parece muy interesante ya que estas consultando una Guia de Remisión y no una boleta/factura/etc. como en el ejemplo que yo adjunté.

Una pregunta que URL usas para consultar "Guias de remisión", es https://e-factura.sunat.gob.pe/ol-it-wsconscpegem/billConsultService? u otra?

Si hay algo que mejorar me gustaria mejorar la libreria para poder cubrir todos los casos, incluyendo el tuyo.

**Comment by geraldvaras** [comment]
@carlosthe19916 en este caso mi proveedor (**bizlinks**) usa una única url para para todas las operaciones relacionas a la facturación electrónica.
[https://osetesting.bizlinks.com.pe/ol-ti-itcpe/billService?wsdl](url).
He estado probando la librería para las demás operaciones y funcionan a la perfección, y es de gran ayuda.
Espero poder colaborar con la misma.
Salu2,

**Comment by carlosthe19916** [comment]
@geraldvaras hice un par de pruebas y la libreria funciona correctamente usando:
- URL = https://osetesting.bizlinks.com.pe/ol-ti-itcpe/billService?wsdl
- GUIA DE REMISION

Al parecer tu proveedor no funciona exactamente como la SUNAT lo hace.

![Screenshot from 2020-09-22 20-15-29](https://user-images.githubusercontent.com/2582866/93922182-e1a24180-fd11-11ea-84f4-5e1f52f1543f.png)

**Comment by geraldvaras** [comment]
Si efectivamente no funciona como SUNAT lo hace, Que me recomendarías para este caso.
De antemano gracias por tu respuesta.

**Comment by carlosthe19916** [comment]
@geraldvaras 

- La primera recomendación es ponerte en contacto con tu proveedor y reportar este error ya que las OSE deben de funcionar tal y como la SUNAT lo hace. Ellos deben de corregir este error.

- Lo segundo que puedo recomendar es que las consultas a `BillConsultServiceManager.getStatusCDR` los hagas directamente a la SUNAT y no a tu proveedor. De esta forma **envías tus comprobantes a traves de tu proveedor** pero cuando desees verificar el CDR de un comprobante lo hagas directamente de la SUNAT. Al final tu proveedor debe de enviar tus comprobantes a la SUNAT por lo que debería de funcionar.
