### ISSUE TITLE
Error 2638 no incluido en la lista de errores

### ISSUE THREAD

**Issue by geraldvaras** [project-openubl/xsender#16]
Al momento de capturar la excepción del rechazo de un comprobante no esta incluido algunos códigos de error. 
Debería existir una forma de incluir códigos de error adicional.
**Screenshots**
![imagen](https://user-images.githubusercontent.com/882405/95368083-39f14b80-089b-11eb-8533-a9b62dc04264.png)
Esta la descripción del código de error "Si tiene operaciones de un tributo en alguna linea, debe consignar el tag del total del tributo."

**Comment by carlosthe19916** [comment]
Gracias por el feedback @geraldvaras; aún cuando al descripción del error no esté presente, tu siempre puedes tener la lista actualizada en tu propio sistema y hacer un mapeo entre el código de error emitido por `xsender` y la descripción almacenada en tu sistema; claro que esto no es lo más optimo por lo que es mejor incluir los códigos en el mismo `xsender`.

**Lo mejor es actualizar el código fuente e incrementar la lista de códigos y descripciones**
¿Te gustaría agregar los códigos y descripciones que no están presentes? Puedes hacer una contribución al proyecto creando un `Pull request`. Lo único que necesitas hacer es hacer un `fork` al proyecto y despues clonar tu `fork` en tu computador, luego puedes abrir el código fuente con un editor e incrementar los códigos y descripciones en https://github.com/project-openubl/xsender/blob/master/src/main/java/io/github/project/openubl/xmlsenderws/webservices/utils/SunatErrors.java . Aqui hay una guía de cómo crear un `pull request` https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/

Tan pronto como se tenga una nueva lista en https://github.com/project-openubl/xsender/blob/master/src/main/java/io/github/project/openubl/xmlsenderws/webservices/utils/SunatErrors.java yo puedo crear un nuevo release que incluya los nuevos cambios y estará disponible en https://mvnrepository.com/artifact/io.github.project-openubl/xsender
